FROM golang:1.9.2-alpine

ARG APP_VERSION=unkown

ADD . /go/src/github.com/vtomasr5/mgob

WORKDIR /go/src/github.com/vtomasr5/mgob

RUN mkdir -p /dist
RUN go build -ldflags "-X main.version=$APP_VERSION" -o /dist/mgob github.com/vtomasr5/mgob

CMD ["ls"]
